[package]
name = "paradoc"
version = "0.1.0"
authors = ["Brian Chen <brian.chxn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.1"
regex = "1"
num-traits = "0.2"
